/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfessionalWorkspaceRouteImport } from './routes/professional-workspace'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AttestTokenRouteImport } from './routes/attest.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace.index'
import { Route as AuthenticatedWorkspaceCapabilityRouteImport } from './routes/_authenticated/workspace.capability'
import { Route as AuthenticatedWorkspaceCoachingRouteImport } from './routes/_authenticated/workspace.coaching'
import { Route as AuthenticatedWorkspaceEvidenceRouteImport } from './routes/_authenticated/workspace.evidence'
import { Route as AuthenticatedWorkspaceOrganisationRouteImport } from './routes/_authenticated/workspace.organisation'
import { Route as AuthenticatedWorkspaceProfileRouteImport } from './routes/_authenticated/workspace.profile'
import { Route as AuthenticatedWorkspaceTeamRouteImport } from './routes/_authenticated/workspace.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalWorkspaceRoute = ProfessionalWorkspaceRouteImport.update({
  id: '/professional-workspace',
  path: '/professional-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AttestTokenRoute = AttestTokenRouteImport.update({
  id: '/attest/$token',
  path: '/attest/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCapabilityRoute =
  AuthenticatedWorkspaceCapabilityRouteImport.update({
    id: '/capability',
    path: '/capability',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCoachingRoute =
  AuthenticatedWorkspaceCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceEvidenceRoute =
  AuthenticatedWorkspaceEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceOrganisationRoute =
  AuthenticatedWorkspaceOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceProfileRoute =
  AuthenticatedWorkspaceProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceTeamRoute =
  AuthenticatedWorkspaceTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/attest/$token': typeof AttestTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/attest/$token': typeof AttestTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/attest/$token': typeof AttestTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/_authenticated/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/_authenticated/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/_authenticated/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/_authenticated/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/_authenticated/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/resources'
    | '/signup'
    | '/terms'
    | '/onboarding'
    | '/workspace'
    | '/attest/$token'
    | '/invite/$token'
    | '/workspace/capability'
    | '/workspace/coaching'
    | '/workspace/evidence'
    | '/workspace/organisation'
    | '/workspace/profile'
    | '/workspace/team'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/resources'
    | '/signup'
    | '/terms'
    | '/onboarding'
    | '/attest/$token'
    | '/invite/$token'
    | '/workspace/capability'
    | '/workspace/coaching'
    | '/workspace/evidence'
    | '/workspace/organisation'
    | '/workspace/profile'
    | '/workspace/team'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/resources'
    | '/signup'
    | '/terms'
    | '/_authenticated/onboarding'
    | '/_authenticated/workspace'
    | '/attest/$token'
    | '/invite/$token'
    | '/_authenticated/workspace/capability'
    | '/_authenticated/workspace/coaching'
    | '/_authenticated/workspace/evidence'
    | '/_authenticated/workspace/organisation'
    | '/_authenticated/workspace/profile'
    | '/_authenticated/workspace/team'
    | '/_authenticated/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CookiesRoute: typeof CookiesRoute
  ExperienceRoute: typeof ExperienceRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LaunchpadRoute: typeof LaunchpadRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalWorkspaceRoute: typeof ProfessionalWorkspaceRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AttestTokenRoute: typeof AttestTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-workspace': {
      id: '/professional-workspace'
      path: '/professional-workspace'
      fullPath: '/professional-workspace'
      preLoaderRoute: typeof ProfessionalWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/attest/$token': {
      id: '/attest/$token'
      path: '/attest/$token'
      fullPath: '/attest/$token'
      preLoaderRoute: typeof AttestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/capability': {
      id: '/_authenticated/workspace/capability'
      path: '/capability'
      fullPath: '/workspace/capability'
      preLoaderRoute: typeof AuthenticatedWorkspaceCapabilityRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/coaching': {
      id: '/_authenticated/workspace/coaching'
      path: '/coaching'
      fullPath: '/workspace/coaching'
      preLoaderRoute: typeof AuthenticatedWorkspaceCoachingRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/evidence': {
      id: '/_authenticated/workspace/evidence'
      path: '/evidence'
      fullPath: '/workspace/evidence'
      preLoaderRoute: typeof AuthenticatedWorkspaceEvidenceRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/organisation': {
      id: '/_authenticated/workspace/organisation'
      path: '/organisation'
      fullPath: '/workspace/organisation'
      preLoaderRoute: typeof AuthenticatedWorkspaceOrganisationRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/profile': {
      id: '/_authenticated/workspace/profile'
      path: '/profile'
      fullPath: '/workspace/profile'
      preLoaderRoute: typeof AuthenticatedWorkspaceProfileRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/team': {
      id: '/_authenticated/workspace/team'
      path: '/team'
      fullPath: '/workspace/team'
      preLoaderRoute: typeof AuthenticatedWorkspaceTeamRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceCapabilityRoute: typeof AuthenticatedWorkspaceCapabilityRoute
  AuthenticatedWorkspaceCoachingRoute: typeof AuthenticatedWorkspaceCoachingRoute
  AuthenticatedWorkspaceEvidenceRoute: typeof AuthenticatedWorkspaceEvidenceRoute
  AuthenticatedWorkspaceOrganisationRoute: typeof AuthenticatedWorkspaceOrganisationRoute
  AuthenticatedWorkspaceProfileRoute: typeof AuthenticatedWorkspaceProfileRoute
  AuthenticatedWorkspaceTeamRoute: typeof AuthenticatedWorkspaceTeamRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceCapabilityRoute:
      AuthenticatedWorkspaceCapabilityRoute,
    AuthenticatedWorkspaceCoachingRoute: AuthenticatedWorkspaceCoachingRoute,
    AuthenticatedWorkspaceEvidenceRoute: AuthenticatedWorkspaceEvidenceRoute,
    AuthenticatedWorkspaceOrganisationRoute:
      AuthenticatedWorkspaceOrganisationRoute,
    AuthenticatedWorkspaceProfileRoute: AuthenticatedWorkspaceProfileRoute,
    AuthenticatedWorkspaceTeamRoute: AuthenticatedWorkspaceTeamRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CookiesRoute: CookiesRoute,
  ExperienceRoute: ExperienceRoute,
  HowItWorksRoute: HowItWorksRoute,
  LaunchpadRoute: LaunchpadRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalWorkspaceRoute: ProfessionalWorkspaceRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AttestTokenRoute: AttestTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
