/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfessionalWorkspaceRouteImport } from './routes/professional-workspace'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AttestTokenRouteImport } from './routes/attest.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PortfolioTokenRouteImport } from './routes/portfolio.$token'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesPmPortfolioRouteImport } from './routes/resources.pm-portfolio'
import { Route as ResourcesStarInterviewStoriesRouteImport } from './routes/resources.star-interview-stories'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace.index'
import { Route as AuthenticatedWorkspaceApplicationsRouteImport } from './routes/_authenticated/workspace.applications'
import { Route as AuthenticatedWorkspaceCapabilityRouteImport } from './routes/_authenticated/workspace.capability'
import { Route as AuthenticatedWorkspaceCoachingRouteImport } from './routes/_authenticated/workspace.coaching'
import { Route as AuthenticatedWorkspaceEvidenceRouteImport } from './routes/_authenticated/workspace.evidence'
import { Route as AuthenticatedWorkspaceExperienceRouteImport } from './routes/_authenticated/workspace.experience'
import { Route as AuthenticatedWorkspaceInboxRouteImport } from './routes/_authenticated/workspace.inbox'
import { Route as AuthenticatedWorkspaceInterviewRouteImport } from './routes/_authenticated/workspace.interview'
import { Route as AuthenticatedWorkspaceLaunchpadRouteImport } from './routes/_authenticated/workspace.launchpad'
import { Route as AuthenticatedWorkspaceOrganisationRouteImport } from './routes/_authenticated/workspace.organisation'
import { Route as AuthenticatedWorkspaceProfileRouteImport } from './routes/_authenticated/workspace.profile'
import { Route as AuthenticatedWorkspaceProjectsRouteImport } from './routes/_authenticated/workspace.projects'
import { Route as AuthenticatedWorkspaceReviewRouteImport } from './routes/_authenticated/workspace.review'
import { Route as AuthenticatedWorkspaceReviewsRouteImport } from './routes/_authenticated/workspace.reviews'
import { Route as AuthenticatedWorkspaceTeamRouteImport } from './routes/_authenticated/workspace.team'
import { Route as AuthenticatedWorkspaceTimelineRouteImport } from './routes/_authenticated/workspace.timeline'
import { Route as AuthenticatedWorkspaceExperienceIndexRouteImport } from './routes/_authenticated/workspace.experience.index'
import { Route as AuthenticatedWorkspaceExperienceTaskKeyRouteImport } from './routes/_authenticated/workspace.experience.$taskKey'
import { Route as ApiPublicMonitoringClientErrorRouteImport } from './routes/api/public/monitoring/client-error'
import { Route as ApiPublicMonitoringHealthRouteImport } from './routes/api/public/monitoring/health'
import { Route as ApiPublicMonitoringUptimeRouteImport } from './routes/api/public/monitoring/uptime'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalWorkspaceRoute = ProfessionalWorkspaceRouteImport.update({
  id: '/professional-workspace',
  path: '/professional-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AttestTokenRoute = AttestTokenRouteImport.update({
  id: '/attest/$token',
  path: '/attest/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTokenRoute = PortfolioTokenRouteImport.update({
  id: '/portfolio/$token',
  path: '/portfolio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPmPortfolioRoute = ResourcesPmPortfolioRouteImport.update({
  id: '/resources/pm-portfolio',
  path: '/resources/pm-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesStarInterviewStoriesRoute =
  ResourcesStarInterviewStoriesRouteImport.update({
    id: '/resources/star-interview-stories',
    path: '/resources/star-interview-stories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceApplicationsRoute =
  AuthenticatedWorkspaceApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCapabilityRoute =
  AuthenticatedWorkspaceCapabilityRouteImport.update({
    id: '/capability',
    path: '/capability',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCoachingRoute =
  AuthenticatedWorkspaceCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceEvidenceRoute =
  AuthenticatedWorkspaceEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceExperienceRoute =
  AuthenticatedWorkspaceExperienceRouteImport.update({
    id: '/experience',
    path: '/experience',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceInboxRoute =
  AuthenticatedWorkspaceInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceInterviewRoute =
  AuthenticatedWorkspaceInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceLaunchpadRoute =
  AuthenticatedWorkspaceLaunchpadRouteImport.update({
    id: '/launchpad',
    path: '/launchpad',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceOrganisationRoute =
  AuthenticatedWorkspaceOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceProfileRoute =
  AuthenticatedWorkspaceProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceProjectsRoute =
  AuthenticatedWorkspaceProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceReviewRoute =
  AuthenticatedWorkspaceReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceReviewsRoute =
  AuthenticatedWorkspaceReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceTeamRoute =
  AuthenticatedWorkspaceTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceTimelineRoute =
  AuthenticatedWorkspaceTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceExperienceIndexRoute =
  AuthenticatedWorkspaceExperienceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceExperienceRoute,
  } as any)
const AuthenticatedWorkspaceExperienceTaskKeyRoute =
  AuthenticatedWorkspaceExperienceTaskKeyRouteImport.update({
    id: '/$taskKey',
    path: '/$taskKey',
    getParentRoute: () => AuthenticatedWorkspaceExperienceRoute,
  } as any)
const ApiPublicMonitoringClientErrorRoute =
  ApiPublicMonitoringClientErrorRouteImport.update({
    id: '/api/public/monitoring/client-error',
    path: '/api/public/monitoring/client-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMonitoringHealthRoute =
  ApiPublicMonitoringHealthRouteImport.update({
    id: '/api/public/monitoring/health',
    path: '/api/public/monitoring/health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMonitoringUptimeRoute =
  ApiPublicMonitoringUptimeRouteImport.update({
    id: '/api/public/monitoring/uptime',
    path: '/api/public/monitoring/uptime',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/attest/$token': typeof AttestTokenRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
  '/resources/pm-portfolio': typeof ResourcesPmPortfolioRoute
  '/resources/star-interview-stories': typeof ResourcesStarInterviewStoriesRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workspace/applications': typeof AuthenticatedWorkspaceApplicationsRoute
  '/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/workspace/experience': typeof AuthenticatedWorkspaceExperienceRouteWithChildren
  '/workspace/inbox': typeof AuthenticatedWorkspaceInboxRoute
  '/workspace/interview': typeof AuthenticatedWorkspaceInterviewRoute
  '/workspace/launchpad': typeof AuthenticatedWorkspaceLaunchpadRoute
  '/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/workspace/projects': typeof AuthenticatedWorkspaceProjectsRoute
  '/workspace/review': typeof AuthenticatedWorkspaceReviewRoute
  '/workspace/reviews': typeof AuthenticatedWorkspaceReviewsRoute
  '/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/workspace/timeline': typeof AuthenticatedWorkspaceTimelineRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/experience/$taskKey': typeof AuthenticatedWorkspaceExperienceTaskKeyRoute
  '/api/public/monitoring/client-error': typeof ApiPublicMonitoringClientErrorRoute
  '/api/public/monitoring/health': typeof ApiPublicMonitoringHealthRoute
  '/api/public/monitoring/uptime': typeof ApiPublicMonitoringUptimeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/workspace/experience/': typeof AuthenticatedWorkspaceExperienceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/attest/$token': typeof AttestTokenRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
  '/resources/pm-portfolio': typeof ResourcesPmPortfolioRoute
  '/resources/star-interview-stories': typeof ResourcesStarInterviewStoriesRoute
  '/resources': typeof ResourcesIndexRoute
  '/workspace/applications': typeof AuthenticatedWorkspaceApplicationsRoute
  '/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/workspace/inbox': typeof AuthenticatedWorkspaceInboxRoute
  '/workspace/interview': typeof AuthenticatedWorkspaceInterviewRoute
  '/workspace/launchpad': typeof AuthenticatedWorkspaceLaunchpadRoute
  '/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/workspace/projects': typeof AuthenticatedWorkspaceProjectsRoute
  '/workspace/review': typeof AuthenticatedWorkspaceReviewRoute
  '/workspace/reviews': typeof AuthenticatedWorkspaceReviewsRoute
  '/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/workspace/timeline': typeof AuthenticatedWorkspaceTimelineRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/experience/$taskKey': typeof AuthenticatedWorkspaceExperienceTaskKeyRoute
  '/api/public/monitoring/client-error': typeof ApiPublicMonitoringClientErrorRoute
  '/api/public/monitoring/health': typeof ApiPublicMonitoringHealthRoute
  '/api/public/monitoring/uptime': typeof ApiPublicMonitoringUptimeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/workspace/experience': typeof AuthenticatedWorkspaceExperienceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/experience': typeof ExperienceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professional-workspace': typeof ProfessionalWorkspaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/attest/$token': typeof AttestTokenRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
  '/resources/pm-portfolio': typeof ResourcesPmPortfolioRoute
  '/resources/star-interview-stories': typeof ResourcesStarInterviewStoriesRoute
  '/resources/': typeof ResourcesIndexRoute
  '/_authenticated/workspace/applications': typeof AuthenticatedWorkspaceApplicationsRoute
  '/_authenticated/workspace/capability': typeof AuthenticatedWorkspaceCapabilityRoute
  '/_authenticated/workspace/coaching': typeof AuthenticatedWorkspaceCoachingRoute
  '/_authenticated/workspace/evidence': typeof AuthenticatedWorkspaceEvidenceRoute
  '/_authenticated/workspace/experience': typeof AuthenticatedWorkspaceExperienceRouteWithChildren
  '/_authenticated/workspace/inbox': typeof AuthenticatedWorkspaceInboxRoute
  '/_authenticated/workspace/interview': typeof AuthenticatedWorkspaceInterviewRoute
  '/_authenticated/workspace/launchpad': typeof AuthenticatedWorkspaceLaunchpadRoute
  '/_authenticated/workspace/organisation': typeof AuthenticatedWorkspaceOrganisationRoute
  '/_authenticated/workspace/profile': typeof AuthenticatedWorkspaceProfileRoute
  '/_authenticated/workspace/projects': typeof AuthenticatedWorkspaceProjectsRoute
  '/_authenticated/workspace/review': typeof AuthenticatedWorkspaceReviewRoute
  '/_authenticated/workspace/reviews': typeof AuthenticatedWorkspaceReviewsRoute
  '/_authenticated/workspace/team': typeof AuthenticatedWorkspaceTeamRoute
  '/_authenticated/workspace/timeline': typeof AuthenticatedWorkspaceTimelineRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/workspace/experience/$taskKey': typeof AuthenticatedWorkspaceExperienceTaskKeyRoute
  '/api/public/monitoring/client-error': typeof ApiPublicMonitoringClientErrorRoute
  '/api/public/monitoring/health': typeof ApiPublicMonitoringHealthRoute
  '/api/public/monitoring/uptime': typeof ApiPublicMonitoringUptimeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/workspace/experience/': typeof AuthenticatedWorkspaceExperienceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/forgot-password'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/onboarding'
    | '/workspace'
    | '/attest/$token'
    | '/checkout/return'
    | '/invite/$token'
    | '/portfolio/$token'
    | '/resources/pm-portfolio'
    | '/resources/star-interview-stories'
    | '/resources/'
    | '/workspace/applications'
    | '/workspace/capability'
    | '/workspace/coaching'
    | '/workspace/evidence'
    | '/workspace/experience'
    | '/workspace/inbox'
    | '/workspace/interview'
    | '/workspace/launchpad'
    | '/workspace/organisation'
    | '/workspace/profile'
    | '/workspace/projects'
    | '/workspace/review'
    | '/workspace/reviews'
    | '/workspace/team'
    | '/workspace/timeline'
    | '/workspace/'
    | '/workspace/experience/$taskKey'
    | '/api/public/monitoring/client-error'
    | '/api/public/monitoring/health'
    | '/api/public/monitoring/uptime'
    | '/api/public/payments/webhook'
    | '/workspace/experience/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/forgot-password'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/onboarding'
    | '/attest/$token'
    | '/checkout/return'
    | '/invite/$token'
    | '/portfolio/$token'
    | '/resources/pm-portfolio'
    | '/resources/star-interview-stories'
    | '/resources'
    | '/workspace/applications'
    | '/workspace/capability'
    | '/workspace/coaching'
    | '/workspace/evidence'
    | '/workspace/inbox'
    | '/workspace/interview'
    | '/workspace/launchpad'
    | '/workspace/organisation'
    | '/workspace/profile'
    | '/workspace/projects'
    | '/workspace/review'
    | '/workspace/reviews'
    | '/workspace/team'
    | '/workspace/timeline'
    | '/workspace'
    | '/workspace/experience/$taskKey'
    | '/api/public/monitoring/client-error'
    | '/api/public/monitoring/health'
    | '/api/public/monitoring/uptime'
    | '/api/public/payments/webhook'
    | '/workspace/experience'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/cookies'
    | '/experience'
    | '/forgot-password'
    | '/how-it-works'
    | '/launchpad'
    | '/login'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/professional-workspace'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/_authenticated/onboarding'
    | '/_authenticated/workspace'
    | '/attest/$token'
    | '/checkout/return'
    | '/invite/$token'
    | '/portfolio/$token'
    | '/resources/pm-portfolio'
    | '/resources/star-interview-stories'
    | '/resources/'
    | '/_authenticated/workspace/applications'
    | '/_authenticated/workspace/capability'
    | '/_authenticated/workspace/coaching'
    | '/_authenticated/workspace/evidence'
    | '/_authenticated/workspace/experience'
    | '/_authenticated/workspace/inbox'
    | '/_authenticated/workspace/interview'
    | '/_authenticated/workspace/launchpad'
    | '/_authenticated/workspace/organisation'
    | '/_authenticated/workspace/profile'
    | '/_authenticated/workspace/projects'
    | '/_authenticated/workspace/review'
    | '/_authenticated/workspace/reviews'
    | '/_authenticated/workspace/team'
    | '/_authenticated/workspace/timeline'
    | '/_authenticated/workspace/'
    | '/_authenticated/workspace/experience/$taskKey'
    | '/api/public/monitoring/client-error'
    | '/api/public/monitoring/health'
    | '/api/public/monitoring/uptime'
    | '/api/public/payments/webhook'
    | '/_authenticated/workspace/experience/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CookiesRoute: typeof CookiesRoute
  ExperienceRoute: typeof ExperienceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LaunchpadRoute: typeof LaunchpadRoute
  LoginRoute: typeof LoginRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalWorkspaceRoute: typeof ProfessionalWorkspaceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AttestTokenRoute: typeof AttestTokenRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PortfolioTokenRoute: typeof PortfolioTokenRoute
  ResourcesPmPortfolioRoute: typeof ResourcesPmPortfolioRoute
  ResourcesStarInterviewStoriesRoute: typeof ResourcesStarInterviewStoriesRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiPublicMonitoringClientErrorRoute: typeof ApiPublicMonitoringClientErrorRoute
  ApiPublicMonitoringHealthRoute: typeof ApiPublicMonitoringHealthRoute
  ApiPublicMonitoringUptimeRoute: typeof ApiPublicMonitoringUptimeRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-workspace': {
      id: '/professional-workspace'
      path: '/professional-workspace'
      fullPath: '/professional-workspace'
      preLoaderRoute: typeof ProfessionalWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/attest/$token': {
      id: '/attest/$token'
      path: '/attest/$token'
      fullPath: '/attest/$token'
      preLoaderRoute: typeof AttestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$token': {
      id: '/portfolio/$token'
      path: '/portfolio/$token'
      fullPath: '/portfolio/$token'
      preLoaderRoute: typeof PortfolioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/pm-portfolio': {
      id: '/resources/pm-portfolio'
      path: '/resources/pm-portfolio'
      fullPath: '/resources/pm-portfolio'
      preLoaderRoute: typeof ResourcesPmPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/star-interview-stories': {
      id: '/resources/star-interview-stories'
      path: '/resources/star-interview-stories'
      fullPath: '/resources/star-interview-stories'
      preLoaderRoute: typeof ResourcesStarInterviewStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/applications': {
      id: '/_authenticated/workspace/applications'
      path: '/applications'
      fullPath: '/workspace/applications'
      preLoaderRoute: typeof AuthenticatedWorkspaceApplicationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/capability': {
      id: '/_authenticated/workspace/capability'
      path: '/capability'
      fullPath: '/workspace/capability'
      preLoaderRoute: typeof AuthenticatedWorkspaceCapabilityRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/coaching': {
      id: '/_authenticated/workspace/coaching'
      path: '/coaching'
      fullPath: '/workspace/coaching'
      preLoaderRoute: typeof AuthenticatedWorkspaceCoachingRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/evidence': {
      id: '/_authenticated/workspace/evidence'
      path: '/evidence'
      fullPath: '/workspace/evidence'
      preLoaderRoute: typeof AuthenticatedWorkspaceEvidenceRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/experience': {
      id: '/_authenticated/workspace/experience'
      path: '/experience'
      fullPath: '/workspace/experience'
      preLoaderRoute: typeof AuthenticatedWorkspaceExperienceRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/inbox': {
      id: '/_authenticated/workspace/inbox'
      path: '/inbox'
      fullPath: '/workspace/inbox'
      preLoaderRoute: typeof AuthenticatedWorkspaceInboxRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/interview': {
      id: '/_authenticated/workspace/interview'
      path: '/interview'
      fullPath: '/workspace/interview'
      preLoaderRoute: typeof AuthenticatedWorkspaceInterviewRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/launchpad': {
      id: '/_authenticated/workspace/launchpad'
      path: '/launchpad'
      fullPath: '/workspace/launchpad'
      preLoaderRoute: typeof AuthenticatedWorkspaceLaunchpadRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/organisation': {
      id: '/_authenticated/workspace/organisation'
      path: '/organisation'
      fullPath: '/workspace/organisation'
      preLoaderRoute: typeof AuthenticatedWorkspaceOrganisationRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/profile': {
      id: '/_authenticated/workspace/profile'
      path: '/profile'
      fullPath: '/workspace/profile'
      preLoaderRoute: typeof AuthenticatedWorkspaceProfileRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/projects': {
      id: '/_authenticated/workspace/projects'
      path: '/projects'
      fullPath: '/workspace/projects'
      preLoaderRoute: typeof AuthenticatedWorkspaceProjectsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/review': {
      id: '/_authenticated/workspace/review'
      path: '/review'
      fullPath: '/workspace/review'
      preLoaderRoute: typeof AuthenticatedWorkspaceReviewRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/reviews': {
      id: '/_authenticated/workspace/reviews'
      path: '/reviews'
      fullPath: '/workspace/reviews'
      preLoaderRoute: typeof AuthenticatedWorkspaceReviewsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/team': {
      id: '/_authenticated/workspace/team'
      path: '/team'
      fullPath: '/workspace/team'
      preLoaderRoute: typeof AuthenticatedWorkspaceTeamRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/timeline': {
      id: '/_authenticated/workspace/timeline'
      path: '/timeline'
      fullPath: '/workspace/timeline'
      preLoaderRoute: typeof AuthenticatedWorkspaceTimelineRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/experience/': {
      id: '/_authenticated/workspace/experience/'
      path: '/'
      fullPath: '/workspace/experience/'
      preLoaderRoute: typeof AuthenticatedWorkspaceExperienceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceExperienceRoute
    }
    '/_authenticated/workspace/experience/$taskKey': {
      id: '/_authenticated/workspace/experience/$taskKey'
      path: '/$taskKey'
      fullPath: '/workspace/experience/$taskKey'
      preLoaderRoute: typeof AuthenticatedWorkspaceExperienceTaskKeyRouteImport
      parentRoute: typeof AuthenticatedWorkspaceExperienceRoute
    }
    '/api/public/monitoring/client-error': {
      id: '/api/public/monitoring/client-error'
      path: '/api/public/monitoring/client-error'
      fullPath: '/api/public/monitoring/client-error'
      preLoaderRoute: typeof ApiPublicMonitoringClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/health': {
      id: '/api/public/monitoring/health'
      path: '/api/public/monitoring/health'
      fullPath: '/api/public/monitoring/health'
      preLoaderRoute: typeof ApiPublicMonitoringHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/uptime': {
      id: '/api/public/monitoring/uptime'
      path: '/api/public/monitoring/uptime'
      fullPath: '/api/public/monitoring/uptime'
      preLoaderRoute: typeof ApiPublicMonitoringUptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWorkspaceExperienceRouteChildren {
  AuthenticatedWorkspaceExperienceTaskKeyRoute: typeof AuthenticatedWorkspaceExperienceTaskKeyRoute
  AuthenticatedWorkspaceExperienceIndexRoute: typeof AuthenticatedWorkspaceExperienceIndexRoute
}

const AuthenticatedWorkspaceExperienceRouteChildren: AuthenticatedWorkspaceExperienceRouteChildren =
  {
    AuthenticatedWorkspaceExperienceTaskKeyRoute:
      AuthenticatedWorkspaceExperienceTaskKeyRoute,
    AuthenticatedWorkspaceExperienceIndexRoute:
      AuthenticatedWorkspaceExperienceIndexRoute,
  }

const AuthenticatedWorkspaceExperienceRouteWithChildren =
  AuthenticatedWorkspaceExperienceRoute._addFileChildren(
    AuthenticatedWorkspaceExperienceRouteChildren,
  )

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceApplicationsRoute: typeof AuthenticatedWorkspaceApplicationsRoute
  AuthenticatedWorkspaceCapabilityRoute: typeof AuthenticatedWorkspaceCapabilityRoute
  AuthenticatedWorkspaceCoachingRoute: typeof AuthenticatedWorkspaceCoachingRoute
  AuthenticatedWorkspaceEvidenceRoute: typeof AuthenticatedWorkspaceEvidenceRoute
  AuthenticatedWorkspaceExperienceRoute: typeof AuthenticatedWorkspaceExperienceRouteWithChildren
  AuthenticatedWorkspaceInboxRoute: typeof AuthenticatedWorkspaceInboxRoute
  AuthenticatedWorkspaceInterviewRoute: typeof AuthenticatedWorkspaceInterviewRoute
  AuthenticatedWorkspaceLaunchpadRoute: typeof AuthenticatedWorkspaceLaunchpadRoute
  AuthenticatedWorkspaceOrganisationRoute: typeof AuthenticatedWorkspaceOrganisationRoute
  AuthenticatedWorkspaceProfileRoute: typeof AuthenticatedWorkspaceProfileRoute
  AuthenticatedWorkspaceProjectsRoute: typeof AuthenticatedWorkspaceProjectsRoute
  AuthenticatedWorkspaceReviewRoute: typeof AuthenticatedWorkspaceReviewRoute
  AuthenticatedWorkspaceReviewsRoute: typeof AuthenticatedWorkspaceReviewsRoute
  AuthenticatedWorkspaceTeamRoute: typeof AuthenticatedWorkspaceTeamRoute
  AuthenticatedWorkspaceTimelineRoute: typeof AuthenticatedWorkspaceTimelineRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceApplicationsRoute:
      AuthenticatedWorkspaceApplicationsRoute,
    AuthenticatedWorkspaceCapabilityRoute:
      AuthenticatedWorkspaceCapabilityRoute,
    AuthenticatedWorkspaceCoachingRoute: AuthenticatedWorkspaceCoachingRoute,
    AuthenticatedWorkspaceEvidenceRoute: AuthenticatedWorkspaceEvidenceRoute,
    AuthenticatedWorkspaceExperienceRoute:
      AuthenticatedWorkspaceExperienceRouteWithChildren,
    AuthenticatedWorkspaceInboxRoute: AuthenticatedWorkspaceInboxRoute,
    AuthenticatedWorkspaceInterviewRoute: AuthenticatedWorkspaceInterviewRoute,
    AuthenticatedWorkspaceLaunchpadRoute: AuthenticatedWorkspaceLaunchpadRoute,
    AuthenticatedWorkspaceOrganisationRoute:
      AuthenticatedWorkspaceOrganisationRoute,
    AuthenticatedWorkspaceProfileRoute: AuthenticatedWorkspaceProfileRoute,
    AuthenticatedWorkspaceProjectsRoute: AuthenticatedWorkspaceProjectsRoute,
    AuthenticatedWorkspaceReviewRoute: AuthenticatedWorkspaceReviewRoute,
    AuthenticatedWorkspaceReviewsRoute: AuthenticatedWorkspaceReviewsRoute,
    AuthenticatedWorkspaceTeamRoute: AuthenticatedWorkspaceTeamRoute,
    AuthenticatedWorkspaceTimelineRoute: AuthenticatedWorkspaceTimelineRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CookiesRoute: CookiesRoute,
  ExperienceRoute: ExperienceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LaunchpadRoute: LaunchpadRoute,
  LoginRoute: LoginRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalWorkspaceRoute: ProfessionalWorkspaceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AttestTokenRoute: AttestTokenRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  InviteTokenRoute: InviteTokenRoute,
  PortfolioTokenRoute: PortfolioTokenRoute,
  ResourcesPmPortfolioRoute: ResourcesPmPortfolioRoute,
  ResourcesStarInterviewStoriesRoute: ResourcesStarInterviewStoriesRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiPublicMonitoringClientErrorRoute: ApiPublicMonitoringClientErrorRoute,
  ApiPublicMonitoringHealthRoute: ApiPublicMonitoringHealthRoute,
  ApiPublicMonitoringUptimeRoute: ApiPublicMonitoringUptimeRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
